import { Roboto } from "next/font/google";
import "./globals.css";
import NavBar from "./(components)/NavBar";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar />
      <body className={`${roboto.variable}  antialiased`}>{children}</body>
    </html>
  );
}
